[project]
name = "elevenlabs-live-vc"
version = "1.0.0"
description = "A live voice-changer utilizing elevenlabs voice-cloning API."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "sounddevice==0.5.1",
  "numpy==2.3.2",
  "scipy==1.16.3",
  "python-dotenv==1.0.1",
  "numba==0.63.1",
  "librosa==0.11.0",
  "colorama==0.4.6",
  "elevenlabs==1.12.1",
  "keyboard==0.13.5",
]
